apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry
spec:
  selector:
    matchLabels:
      app: sentry
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
  spec:
    containers:
      - name: memcached
        image: elyes000/memcached:tagVersion
        ports:
          - containerPort: 11211
    volumes:
      - name: sentry
        persipersistentVolumeClaim:
          claimName: sentry-disk
