apiVersion: v1
kind: Service
metadata:
    name: nginx-deployment
    labels:
        app: myapp
spec:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 8080
    selector: 
        tier: front
      