apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry
spec:
  selector:
    matchLabels:
      app: sentry
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
  spec:
    containers:
      - name: sentry
        image: elyes000/postgres:tagVersion
        ports:
          - containerPort: 5432
        resources:
          limits:
            memory: "100Mi"
            cpu: "0.5"
          requests:
            memory: "200Mi"
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: sentry 
            subPath: postgres
    volumes:
      - name: sentry
        persipersistentVolumeClaim:
          claimName: sentry-disk