apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry
spec:
  selector:
    matchLabels:
      app: sentry
  replicas: 1
  template:
    metadata:
      labels:
        app: sentry
  spec:
    containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
        
    volumes:
      - name: sentry
        persipersistentVolumeClaim:
          claimName: sentry-disk
